services:
  - type: web
    name: heart-disease-predictor
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn health_desease.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
